Repository PyBotDevs/skyblockpy, pull requests merged in 2022-12, with the labels that each got.

#1 Make separate API library functions for getting player auctions and all auctions
  api.py
Labels: enhancement, size/S

#2 Add functions for fetching Skyblock Collections and Skills data
  api.py
Labels: enhancement, size/S

#3 Fix library auto-import structure
  __init__.py
Labels: size/XS, patch

#4 Fix errors related to returning API endpoint data
  api.py
Labels: size/S, patch

#5 Add API endpoint request functions for getting data on Skyblock items, mayor information and ongoing election information
  api.py
Labels: enhancement, size/S

#6 Explicitly define API endpoint returns as `dict`
  api.py
Labels: documentation, enhancement, size/S
