Repository PyBotDevs/skyblockpy, pull requests merged in 2024-04, with the labels that each got.

#22 Add `pyproject.toml` configuration
  pyproject.toml
Labels: documentation, enhancement, size/S

#19 Remove all trailing whitespaces
  api.py
Labels: size/S, patch

#20 Simplify Hypixel API documentation link
  README.md
Labels: documentation, size/XS

#21 Update `firesales` API endpoint url
  api.py
Labels: enhancement, size/XS, patch

#23 Add some example code to README
  README.md
Labels: documentation, enhancement, size/M

#24 Switch from using `__init__.py` module to direct `skyblockpy` module
  __init__.py
  skyblockpy.py
Labels: enhancement, size/S
